fib-international/structuralcodes

structuralcodes/codes/ec2_2004/__init__.py
structuralcodes/codes/ec2_2004/_reinforcement_material_properties.py
structuralcodes/codes/mc2010/__init__.py
structuralcodes/codes/mc2010/_reinforcement_material_properties.py
structuralcodes/geometry/_geometry.py
structuralcodes/materials/concrete/__init__.py
structuralcodes/materials/concrete/_concrete.py
structuralcodes/materials/concrete/_concreteEC2_2004.py
structuralcodes/materials/concrete/_concreteEC2_2023.py
structuralcodes/materials/concrete/_concreteMC2010.py
structuralcodes/materials/constitutive_laws.py
structuralcodes/materials/reinforcement/_reinforcement.py
structuralcodes/materials/reinforcement/_reinforcementEC2_2004.py
structuralcodes/materials/reinforcement/_reinforcementEC2_2023.py
structuralcodes/materials/reinforcement/_reinforcementMC2010.py
tests/test_core/test_generic_section.py
tests/test_ec2_2004/test_concrete_ec2_2004.py
tests/test_ec2_2023/test_concrete_ec2_2023.py
tests/test_materials/test_reinforcements.py
tests/test_mc2010/test_concrete_mc2010.py

By default, we should use the design material strengths in the constitutive laws for our material classes. This is a suggestion for how to deal with that.

feat: use design strengths in constitutive laws

---

structuralcodes/core/base.py
structuralcodes/materials/constitutive_laws.py
tests/test_core/test_constitutive_laws.py
tests/test_core/test_generic_section.py

Sargin Constitutive Law is added to the list of Constitutive laws. 
Methods for getting stress and tangent are implemented.
Method for getting Marin coefficients is not yet implemented.
The problem is that it seems impossible to represent Sargin as a polynomial function.
My proposal is the following:
- in the `__marin__` method convert the function to a piecewise linear function using `UserDefined`. Then use `__marin__` from UserDefined. 
- a further possibility is that the default `__marin__` for base class `ConstitutiveLaw` those this use of `UserDefined` law for defining a piecewise linear function, so all constitutive laws that are implemented from now on will have a free `__marin__` function for estimating coefficients. If one can and wants, it is possible to define `__marin__` for …

feat: Add Sargin Constitutive Law to Constitutive laws

---

structuralcodes/codes/ec2_2004/shear.py
tests/test_ec2_2004/test_ec2_2004_shear.py

Updates the calculation of VRdmax according to EC2 2004:
- Uses the predefined function for calculating fcd.
- Introduces a flag for indicating whether the design yield strength of the stirrups is limited or not, to control which strength reduction factor to use for concrete, Eq. (6.6) or (6.10).
The diff looks really weird, so I have added comments at the spots where I have introduced changes.

feat: update vrdmax ec2 2004

---

structuralcodes/sections/_generic.py
tests/test_core/test_generic_section.py

A slight refinement of the `.calculate_moment_curvature` method on the `GenericSectionCalculator`.

feat: refine moment curvature

---

structuralcodes/sections/_generic.py

Update GenericSection to work also with SurfaceGeometry as input.
This fix an issue mentioned in #113 
```
concrete = ConcreteEC2_2004(25)
poly = Polygon(((0, 0), (350, 0), (350, 500), (0, 500)))
geo = SurfaceGeometry(poly, concrete)
sec = GenericSection(geo)
print(f"Area = {sec.gross_properties.area*1e-2} cm2")
sec = GenericSection(CompoundGeometry([geo]))
print(f"Area = {sec.gross_properties.area*1e-2} cm2") 
```
now both definition works and the output is:
```
Area = 1750.0 cm2
Area = 1750.0 cm2
```

fix: Update GenericSection to accept SurfaceGeometry

---

structuralcodes/materials/concrete/_concrete.py
structuralcodes/materials/constitutive_laws.py
tests/test_core/test_generic_section.py

Fixed a bug in parabola-rectangle constitutive law function for evaluation of Marin coefficients. The computation of the coefficients assumed the exponent of the parabolic part is equal to 2. If the exponent is different than 2, the marin method for all constitutive laws (even if less efficient) is called.

fix: bugfix marin coefficients

---

makefile
structuralcodes/core/_section_results.py
structuralcodes/sections/_generic.py
tests/test_core/test_generic_section.py
tests/test_core/test_steel_sections.py

This PR addresses the issues in #156.
For functions `calculate_nm_interaction_domain` and `calculate_nmm_interaction_domain` the API was extended permitting a finer control on discretization of strain profiles.
By default a reasonable discretization is proposed. The user can specified the number of discretizations for each failure field (from 1 to 6) and eventually the typology of spacing. The supported spacing rules are: linear, geometric, quadratic.
For instance, setting all numbers to 1:
```
mn_results = section.section_calculator.calculate_nm_interaction_domain(n1=1,n2=1,n3=1,n4=1,n5=1,n6=1)
```
Leads to the following result in MN domain:
The points are corresponding to ultimate strain profiles shown in the following:
By default all fields are discretized linearly, except field 3 that …

fix: improve API for interaction domain

---

docs/quickstart/index.md

A change in one of the early code lines of the quickstart example lead to lines below not being visible.

docs: fix visible lines in quickstart example

---

README.md
docs/index.md
docs/versioning/index.md

Add a description of how we handle versioning in the docs. In short we say that the API of StructuralCodes is not yet stable. When the API is stable we will increase the major version to 1.0.0. Until then, we will indicate backwards incompatible changes by an increase of the minor version number.
This is loosly inspired by the current versioning scheme used by [Ruff](https://docs.astral.sh/ruff/versioning/).

docs: describe versioning

---

structuralcodes/geometry/_steel_sections.py

Solves an issue where a call to `.Wely` or `.Welz` on a steel section raised a `TypeError` if not `.Iy` and `.Iz` was called from before.

bug: fix calculating Wely and Welz on steel sections

---

structuralcodes/core/base.py
structuralcodes/materials/constitutive_laws.py
structuralcodes/sections/_generic.py
tests/test_core/test_constitutive_laws.py

The `get_ultimate_strain` method on `ConstitutiveLaw`s returns a tuple of strains. In the current implementation, it returns the positive strain first, and then the negative strain. It is perhaps more intuitive if we swap these, so that the returned strain limits are from left to right in a typical stress-strain diagram, or from low to high with respect to value. This is an attempt to swap the values.

fix: swap order of strain limits returned from get_ultimate_strain

---

docs/api/sections/section_calculator.md
structuralcodes/core/_section_results.py
structuralcodes/sections/_generic.py

In this PR I refactored slightly the Interaction Domain Results in order to be consistent.
I am proposing to keep strains and forces arrays as the real data (this can be helpful for dealing with the data in an efficient way for further processing of the data) plus creating properties for returning easily for the user the specific forces (n, m_y, m_z) and strain (ea, k_y, k_z).
For instance, this code creates and plots an interaction domain of a rectangular cross section.
```
import matplotlib.pyplot as plt
import numpy as np
from shapely import Polygon
from structuralcodes.codes import set_design_code
from structuralcodes.geometry import SurfaceGeometry
from structuralcodes.materials.concrete import create_concrete
from structuralcodes.materials.reinforcement import create_reinforcement …
```

fix: interaction domain results

---

structuralcodes/sections/_generic.py

Specifies in the docstrings of section calculator methods that the unit of the angle of the neutral axis is radians.

fix: specify unit theta

---

structuralcodes/codes/__init__.py
tests/test_core/test_get_set_design_code.py

Allows to pass a module to the `set_design_code` function, and improves the robustness of the method.

feat: more robust set design code

---

structuralcodes/codes/mc2010/_concrete_creep_and_shrinkage.py

Correct the calculated value of `beta_ds` when the requested time is less than the time at start of exposure. This is necessary for correct computation of shrinkage development when an array of time from zero is provided.

fix: mc2010 beta_ds correct for time less than ts

---

structuralcodes/geometry/_reinforcement.py
tests/test_core/test_geometry.py

Add the keyword argument `group_label` to the functions for adding reinforcement. This way, the created reinforcement is assigned the group label, and we prepare for other functions that can select based on the label.

feat: add kwarg group_label to add_reinforcement functions

---

structuralcodes/codes/ec2_2004/shear.py

The parameter `CRdc` appears in Eq. (6.2) in EC2 (2004), but was not provided as an argument to the relevant function in `structuralcodes.codes.ec2_2004`.
Here, the parameter is added with a default value `None`. If no further value is provided, the default value from the design code `0.18 / gamma_c` will be used, otherwise, the provided value will be used.

feat: ec2-2004 expose crdc in shear resistance

---

structuralcodes/sections/_generic.py

In our calculation of the cross moment Iyz for generic sections, we raise a `RuntimeError` if the two ways of calculating the moment does not result in values that are close enough. In the current version we check only the absolute value of these results, but this is too strict if the section has a value of the cross moment significantly different from zero.
This is an attempt to liberalize the check by introducing a relative check in addition by using the `math.isclose` function. The absolute tolerance used in `isclose` is rather liberal, but the value is kept equal to the existing implementation.
Although beyond the scope of the PR, I have also changed `math.sin` and `math.cos` to the `numpy` versions of the functions to have a cleaner import block.

fix: use also relative tolerance when checking calculated Iyz

---

docs/api/sections/section_calculator.md
structuralcodes/sections/_generic.py

An attempt to clarify that we can pass keyword arguments to the section calculator and the section integrator when initializing a section.

docs: improve description of kwargs passed from section to calculator

---

structuralcodes/sections/section_integrators/_fiber_integrator.py

When using meters as unit length the maximum area used for triangulation is a very small number and then was not properly used in current implementation. Fixed this behavior.

fix: bugfix triangulation

---

structuralcodes/geometry/_geometry.py

When translating or rotating a SurfaceGeometry or CompoundGeometry we have to pass also the concrete argument to the init method.

fix: reinforced concrete property

---

structuralcodes/geometry/_geometry.py
structuralcodes/sections/_generic.py
tests/test_core/test_generic_section.py

This PR solves the bug spot by @MestreCarlos in #163.
Now the following code snippet provided by @MestreCarlos:
```
import math
from pprint import pprint
from shapely import Polygon
from structuralcodes.geometry import SurfaceGeometry
from structuralcodes.materials.concrete import ConcreteEC2_2004
from structuralcodes.materials.reinforcement import ReinforcementEC2_2023
from structuralcodes.sections._generic import GenericSection
from structuralcodes.geometry import add_reinforcement_line
concrete = ConcreteEC2_2004(25)
reinforcement = ReinforcementEC2_2023(
fyk=500, Es=200000, density=7850, ftk=550, epsuk=0.07
)
poly = Polygon(((0, 0), (350, 0), (350, 500), (0, 500)))
geo = SurfaceGeometry(poly, concrete)
geo = add_reinforcement_line(
geo, (50, 450), (300, 450), 20, reinforcement, n=10
) …
```

fix: rotate strain in result from bending strength

---

structuralcodes/codes/ec2_2004/_concrete_creep_and_shrinkage.py
structuralcodes/codes/mc2010/_concrete_creep_and_shrinkage.py
structuralcodes/geometry/_geometry.py
tests/test_mc2010/test_mc2010_creep_and_shrinkage.py

A minor update to the creep and shrinkage calculations according to MC2010 to make it alligned with EC2_2004. The main change is related to calculation of `beta_ds`.
Two additional very minor fixes that should have been part of #194 and #203.

fix: check if input to mc2010 creep and shrinkage is scalar

---

docs/api/geometry/geometry_creation.md
structuralcodes/geometry/__init__.py
structuralcodes/geometry/_circular.py
structuralcodes/geometry/_geometry.py
structuralcodes/geometry/_reinforcement.py
tests/test_core/test_circular.py

This PR includes a wrapper utility for creating circular geometries.
There is a `CircularGeometry` that represents a `SurfaceGeometry` with a circular shape. It can be created with:
```
circle = CircularGeometry(300, material)
```
Where 300 is the size of the section (by default it is the diameter, unless the argument `is_radius` is set to `True`) and material is a valid `Material` or `ConstitutiveLaw` object.
The resulting geometry can be further worked editing it with additions, subtractions, transformations. When the geometry is set, that can be assigned to a `GenericSection` to perform the computations.
Then a utility method inside `_reinforcement` named `add_reinforcement_circle` has been included permitting by default the distribution of `n` given bars (or given the spacing `s`) …

feat: Add circular geometries

---

structuralcodes/geometry/_circular.py
structuralcodes/geometry/_rectangular.py
tests/test_geometry/test_circular.py
tests/test_geometry/test_rectangular.py

I have added a kwarg to both the `CircularGeometry` and the `RectangularGeometry` to easily set the origin of the geometry to a point other than `(0.0, 0.0)`.

feat: add origin kwarg to wrapper geom classes

---

structuralcodes/materials/constitutive_laws/_bilinearcompression.py
tests/test_materials/test_constitutive_laws.py

Fixes #215 
Updated the code, so the approach for arrays and scalars are the same. and added scalar to the test

fix: get_stress in BilinearCompression

---

structuralcodes/core/base.py

This annotation was accidentally removed in #226.

fix: annotate constitutive law property of base material

---

.vscode/settings.json
structuralcodes/sections/_generic.py

Solved a bug for which the yield strain is used in computing the balanced failure strain plane if the section is not of reinforced concrete.

fix: bugfix mn domain

---

structuralcodes/sections/_generic.py
tests/test_sections/test_generic_section.py

This commit fixes the bug for which results where inconsistent if evaluating the bending strength for an angle different than zero as the first computation on the section. Indeed the triangulation is created on the section without account the rotation of the section during computation of the strength.

fix: bugfix rotation triangulation data

---

structuralcodes/sections/section_integrators/_shell_integrator.py

In `integrate_stress`, the unpacking `z, stress_resultants = prepared_input[0]` might be misleading, since `stress_resultants` here is the array of per-fiber stress contributions from `prepare_input`.

fix: replace misleading variable name in integrate_stress method

---

structuralcodes/geometry/_circular.py
structuralcodes/geometry/_geometry.py
structuralcodes/geometry/_rectangular.py
structuralcodes/geometry/_reinforcement.py
structuralcodes/materials/__init__.py
structuralcodes/materials/basic/__init__.py
structuralcodes/materials/basic/_elastic.py
structuralcodes/materials/basic/_elasticplastic.py
structuralcodes/materials/basic/_generic.py
structuralcodes/sections/_generic.py
structuralcodes/sections/_rc_utils.py
structuralcodes/sections/section_integrators/_fiber_integrator.py
structuralcodes/sections/section_integrators/_marin_integrator.py
tests/test_geometry/test_circular.py
tests/test_geometry/test_geometry.py
tests/test_geometry/test_rectangular.py
tests/test_geometry/test_steel_sections.py
tests/test_sections/test_generic_section.py

Removes the option to pass a constitutive law when creating a geometry. Instead, only material objects are allowed.
The following tasks were done:
- Allow only material objects when creating geometry objects.
- Add basic material objects with basic constitutive laws.
- Update tests.

feat: use only material objects in geometry objects

---

structuralcodes/materials/concrete/_concreteEC2_2004.py
structuralcodes/materials/concrete/_concreteEC2_2023.py
structuralcodes/materials/concrete/_concreteMC2010.py
tests/test_materials/test_concrete.py

This PR is a tentative solution for fixing the wrong initial stiffness read by `get_tangent(0.0)` method in `concrete`. 
The relation k_sargin (taken from (3.14) in EC2 was computed with reference to `fcm`. This PR makes this calculation with reference to fcd. The tests are broken now of course, but I will update them if we decide this could be the correct solution.
See the difference between the old (dashed orange line) and the current implementation (blue solid line).
This has ben corrected for EC2 2004 and EC2 2023. Not for MC2010 that is more tricky since gives values for given fck in a tabular format so making it harder deciding how to correct it when the law represents `fcd` instead of `fcm`.

fix: Update __sargin__  with k_sargin computed using fcd and not fcm

---

structuralcodes/codes/ec2_2004/shear.py
tests/test_ec2_2004/test_ec2_2004_shear.py

A large axial force in tension could result in a negative shear capacity. This fixes the behavior, and ensures the capacity is non-negative.

fix: make sure VRdc according to EC2-2004 is non-negative
